# Generated by Django 2.0.1 on 2020-05-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='food_pref',
            field=models.CharField(choices=[('veg', 'veg'), ('nonveg', 'nonveg')], default='veg', max_length=5),
        ),
    ]
