# Generated by Django 2.0.1 on 2020-05-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_food_pref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='food_pref',
        ),
        migrations.AddField(
            model_name='customer',
            name='food_pref',
            field=models.CharField(default='veg', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(default='restaurant', max_length=100),
            preserve_default=False,
        ),
    ]
