# Generated by Django 2.2 on 2020-05-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200527_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(default='dhaba', max_length=100),
            preserve_default=False,
        ),
    ]
