# Generated by Django 2.0.1 on 2020-05-28 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=20)),
                ('dish_type', models.CharField(default='veg', max_length=10)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('restaurant_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu_details',
            },
        ),
    ]
