# Generated by Django 2.2 on 2020-05-30 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='none', max_length=100)),
                ('dish_name', models.CharField(max_length=20)),
                ('dish_type', models.CharField(choices=[('veg', 'veg'), ('nonveg', 'nonveg')], default='veg', max_length=10)),
                ('price', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'db_table': 'menu_details',
            },
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='none', max_length=100)),
                ('restaurant_name', models.CharField(default='none', max_length=100)),
                ('dish_name', models.CharField(max_length=20)),
                ('dish_type', models.CharField(choices=[('veg', 'veg'), ('nonveg', 'nonveg')], default='veg', max_length=10)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2020, 5, 30, 15, 33, 59, 489965))),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
    ]
