# Generated by Django 2.2.12 on 2020-05-28 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_details',
            name='dish_type',
            field=models.CharField(choices=[('veg', 'veg'), ('nonveg', 'nonveg')], default='veg', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu_details',
            name='restaurant_name',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
