# Generated by Django 2.2 on 2020-05-30 11:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0002_auto_20200530_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_details',
            name='restaurant_name_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu_details',
            name='restaurant_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 16, 46, 19, 932293)),
        ),
    ]
