# Generated by Django 2.2.12 on 2020-05-28 15:15

import django.contrib.auth.base_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200528_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_details',
            name='restaurant_name',
            field=models.CharField(choices=[('name', django.contrib.auth.base_user.AbstractBaseUser.get_username)], default='none', max_length=100),
        ),
    ]
