# Generated by Django 2.2.12 on 2020-05-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200528_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='none', max_length=100)),
                ('customer_details', models.CharField(default='none', max_length=100)),
                ('dish_name', models.CharField(max_length=20)),
                ('dish_type', models.CharField(choices=[('veg', 'veg'), ('nonveg', 'nonveg')], default='veg', max_length=10)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
        migrations.AlterField(
            model_name='menu_details',
            name='restaurant_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
