# Generated by Django 2.2 on 2020-05-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200529_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='image',
        ),
    ]
