# Generated by Django 2.2 on 2020-05-29 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_order_details_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='customer_details',
            new_name='customer_name',
        ),
        migrations.AddField(
            model_name='order_details',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 21, 13, 56, 877973)),
        ),
    ]
