# Generated by Django 2.2 on 2020-06-02 09:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_auto_20200530_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_details',
            name='image',
        ),
        migrations.AlterField(
            model_name='menu_details',
            name='restaurant',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 14, 51, 52, 636815)),
        ),
    ]
